org: darbados
app: transactions-handler
service: transactions-handler

projectDir: ./

frameworkVersion: '2'


provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-west-3
  stackName: TransactionHandler
  apiName: TransactionsAPI
  memorySize: 128
  lambdaHashingVersion: 20201221
  logs:
    restApi: true
  environment:
    DB_TABLE_NAME: 'transactions-${self:provider.stage}'

plugins:
  - serverless-s3-sync
  - serverless-python-requirements
  - serverless-offline

custom:
  s3Sync:
    - bucketName: transactions-storage-bucket-230721
      localDir: assets

functions:
  index:
    handler: lambdas/index.handler
    events:
      - http:
          path: /
          method: GET
          cors: true
  saveTransaction:
    handler: lambdas/transaction.handler
    events:
      - http:
          path: transactions/save
          method: POST
          cors: true

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: transactions-storage-bucket-230721
    TransactionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DB_TABLE_NAME}
